theme: osuny
_merge: deep
params:
  additional_csp: 'newassets.hcaptcha.com'
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site